### ISSUE TITLE
建议~最好加个当前环境的requirements.list

### ISSUE THREAD

**Issue by cjj0596** [big-loser/kubernetes-ansible#2]
可以知道当前使用有什么模块，也方便部署~

**Comment by big-loser** [comment]
非常感谢你的建议，你说的模块是ansible的模块吗 ？ 还是其他的 ？

**Comment by cjj0596** [comment]
就是运行需要的依赖吧，因为之前用过ansible1.9.x和2.0以上的也有区别。

**Comment by big-loser** [comment]
嗯，我刚才看了一下ansible的changelog ，我用到的模块还有写法，ansible 版本 1.2 以后都能运行 。

回头我把这个东西加上。先close了
