### ISSUE TITLE
执行到TASK [master : 启动服务] 报错

### ISSUE THREAD

**Issue by cjj0596** [big-loser/kubernetes-ansible#3]
Aug 15 18:04:17 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.

docker服务启动失败
环境是centos7.3

**Comment by cjj0596** [comment]
Aug 15 18:04:17 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 15 18:04:17 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.
Aug 15 18:05:48 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 15 18:05:48 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.
Aug 15 18:07:18 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 15 18:07:18 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.

**Comment by big-loser** [comment]
你的系统不是全新的？ 

试试  yum install device-mapper-event-libs 然后再启动docker 试试 。

**Comment by cjj0596** [comment]
是的，是centos7.3最小安装的，执行你写的playbook到 [master : 启动服务]  docker服务报错，其他服务正常开启

**Comment by cjj0596** [comment]
Aug 15 23:00:41 docker-40 systemd: Dependency failed for Docker Application Container Engine.
Aug 15 23:00:41 docker-40 systemd: Dependency failed for Run docker-cleanup every hour.
Aug 15 23:00:41 docker-40 systemd: Job docker-cleanup.timer/start failed with result 'dependency'.
Aug 15 23:00:41 docker-40 systemd: Job docker.service/start failed with result 'dependency'.

这是/var/log/messages的信息，知道是什么原因吗？

**Comment by cjj0596** [comment]
TASK [etcd : 创建ETCD目录] **********************************************************************************************************************************************************************
fatal: [192.168.0.40]: FAILED! => {"changed": true, "cmd": "etcdctl mkdir /kube-centos/network", "delta": "0:00:00.024928", "end": "2017-08-15 18:14:58.192872", "failed": true, "rc": 4, "start": "2017-08-15 18:14:58.167944", "stderr": "Error:  105: Key already exists (/kube-centos/network) [5]", "stderr_lines": ["Error:  105: Key already exists (/kube-centos/network) [5]"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [etcd : 设置集群子网] ************************************************************************************************************************************************************************
fatal: [192.168.0.40]: FAILED! => {"changed": true, "cmd": ["etcdctl", "mk", "/kube-centos/network/config", "{ \"Network\": \"192.168.0.0/24\", \"SubnetLen\": 24, \"Backend\": { \"Type\": \"vxlan\" } }"], "delta": "0:00:00.025020", "end": "2017-08-15 18:14:58.644618", "failed": true, "rc": 4, "start": "2017-08-15 18:14:58.619598", "stderr": "Error:  105: Key already exists (/kube-centos/network/config) [5]", "stderr_lines": ["Error:  105: Key already exists (/kube-centos/network/config) [5]"], "stdout": "", "stdout_lines": []}
...ignoring


跟这两部报错有关系吗？

**Comment by big-loser** [comment]
第一个错误 ，执行 yum install device-mapper-event-libs  以后docker能启动了吗 ？

**Comment by cjj0596** [comment]
不能，提示相同的错误

**Comment by big-loser** [comment]
第二个错误，是因为第一次执行了 etcd的安装，并且etcd已经有KEY 了，再次执行的时候，就会报key已经存在了。不过这个错误已经是忽略了。

**Comment by big-loser** [comment]
systemctl status docker.service and 'journalctl -xn'

**Comment by cjj0596** [comment]
Aug 15 22:58:09 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 15 22:58:09 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.
Aug 15 23:00:41 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 15 23:00:41 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.
Aug 16 10:06:38 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 16 10:06:38 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.
Aug 16 10:15:41 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 16 10:15:41 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.
Aug 16 10:21:37 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 16 10:21:37 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.
Unit and.service could not be found.
Unit journalctl\x20-xn.service could not be found.

**Comment by cjj0596** [comment]
找到原因了
Aug 16 10:30:00 docker-40 docker-storage-setup[1418]: INFO: Volume group backing root filesystem could not be determined
Aug 16 10:30:00 docker-40 docker-storage-setup[1418]: ERROR: Failed to determine existing storage driver.

**Comment by big-loser** [comment]
mv /var/lib/docker /tmp/
mkdir /var/lib/docker 
systemctl start docker

**Comment by big-loser** [comment]
你的系统盘是 LVM ？

**Comment by cjj0596** [comment]
没有，就只有一个根目录

**Comment by cjj0596** [comment]
[root@docker-40 docker]# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/docker.service.d
           └─flannel.conf
   Active: inactive (dead)
     Docs: http://docs.docker.com

Aug 16 10:26:35 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 16 10:26:35 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.
Aug 16 10:29:54 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 16 10:29:54 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.
Aug 16 10:34:26 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 16 10:34:26 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.
Aug 16 10:37:27 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 16 10:37:27 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.
Aug 16 10:40:53 docker-40 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 16 10:40:53 docker-40 systemd[1]: Job docker.service/start failed with result 'dependency'.
[root@docker-40 docker]# journalctl -xn
-- Logs begin at Tue 2017-08-15 14:38:20 CST, end at Wed 2017-08-16 10:41:28 CST. --
Aug 16 10:41:24 docker-40 flanneld-start[2010]: I0816 10:41:24.906502    2010 local_manager.go:179] Picking subnet in range 192.168.1.0 ... 192.168.0.0
Aug 16 10:41:24 docker-40 flanneld-start[2010]: E0816 10:41:24.906529    2010 network.go:102] failed to register network: failed to acquire lease: out of subnets
Aug 16 10:41:25 docker-40 flanneld-start[2010]: I0816 10:41:25.931157    2010 local_manager.go:179] Picking subnet in range 192.168.1.0 ... 192.168.0.0
Aug 16 10:41:25 docker-40 flanneld-start[2010]: E0816 10:41:25.931188    2010 network.go:102] failed to register network: failed to acquire lease: out of subnets
Aug 16 10:41:26 docker-40 flanneld-start[2010]: I0816 10:41:26.951944    2010 local_manager.go:179] Picking subnet in range 192.168.1.0 ... 192.168.0.0
Aug 16 10:41:26 docker-40 flanneld-start[2010]: E0816 10:41:26.951971    2010 network.go:102] failed to register network: failed to acquire lease: out of subnets
Aug 16 10:41:27 docker-40 flanneld-start[2010]: I0816 10:41:27.972800    2010 local_manager.go:179] Picking subnet in range 192.168.1.0 ... 192.168.0.0
Aug 16 10:41:27 docker-40 flanneld-start[2010]: E0816 10:41:27.972826    2010 network.go:102] failed to register network: failed to acquire lease: out of subnets
Aug 16 10:41:28 docker-40 flanneld-start[2010]: I0816 10:41:28.993575    2010 local_manager.go:179] Picking subnet in range 192.168.1.0 ... 192.168.0.0
Aug 16 10:41:28 docker-40 flanneld-start[2010]: E0816 10:41:28.993602    2010 network.go:102] failed to register network: failed to acquire lease: out of subnets


是不是flanneld设错了？

**Comment by big-loser** [comment]
是， 你说一下，本机网络是多少？  然后在group_var 下配置的是多少 ？

**Comment by cjj0596** [comment]
SERVICE_CIDR: "10.254.0.0/16"

CLUSTER_CIDR: "192.168.0.0/16"

CLUSTER_DNS_SVC_IP: "10.254.0.2"

CLUSTER_KUBERNETES_SVC_IP: "10.254.0.1"

ETCD_SERVER_IP: "http://192.168.0.40:2379"


MASTER_IP: "192.168.0.40"
MINION_1_IP: "192.168.0.41"
MINION_2_IP: "192.168.0.42"

本机就是0.40

**Comment by big-loser** [comment]
CLUSTER_CIDR 这个变量你理解错了， 这个变量不是指集群机器的内网的CIDR。而是指kubernetes 简历以后给POD分的CIDR网络。

所以你这要配置成 "172.30.0.0/16"
