### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by cjj0596** [big-loser/kubernetes-ansible#5]
感谢作者提供的帮助，现在已经全部跑完任务，发现有以下几个小问题：
1. name: 拷贝 kubernetes 二进制包 这一步由于是要下载，所以有时候会等待比较久，而且master和minions都会执行相同的操作，所以建议把安装包直接放到files用copy会快很多

2. 由于我不是用root，而是用具有sudo权限的用户来执行，所以template过去的文件会放到用户的家目录而不是/root下，当下一个任务需要执行命令调用文件就会出错，可以使用      
`args:
         chdir: /root/
`
增加到执行命令的任务中来切换到/root目录再执行命令

3. 在roles/minions/templates/kube-proxy.j2中由于涉及到获取ip地址{{ ansible_eth0.ipv4.address }}，有时候网卡的名称不一定是eth0，所以我要手动改成对应的当前网卡名称才能获取成功

4. 最后的那个任务需要执行
`shell: kubectl create -f https://raw.githubusercontent.com/kubernetes/ingress/master/examples/rbac/nginx/nginx-ingress-controller-service.yml`
是否需要改为
`shell: /opt/kubernetes/bin/kubectl create -f https://raw.githubusercontent.com/kubernetes/ingress/master/examples/rbac/nginx/nginx-ingress-controller-service.yml`

5. 还有一个是我执行该项目的时候是使用ansible-playbook -i hosts site.yaml
    当我执行ansible -i hosts site.yaml会显示[WARNING]: No hosts matched, nothing to do

**Comment by big-loser** [comment]
首先真的非常非常非常感谢的你的使用，并提出这么问题和建议。
对于的问题，我来一个一个回答。
1、这确实是一个问题，我一开始也是想过把包放在file里本地COPY。但是kubernetes的包大小已经超过了github上传限制。另外一个问题，为了兼容1.6.7 版本的部署。所以我选择了。用户自己填写URL方式 。

2、这个回头，我调整把文件放在一个/tmp 这种公用地方。

3、这个问题，我也考虑到了，再上次改版中，在group_var中，需要用户手动填写master,和 minions IP 了，只是这块漏掉了 。 我回头修复一下 。

4、疏忽遗漏。

5、我写的没问题是ansible-playbook ，而你执行的是ansible  。 ansible-playbook 和ansible 两个命令本身不同。所以会出现这个错误。

最后再次感谢你的使用和建议。
